# Generated by Django 3.2 on 2023-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_employee_joine'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Mobile_num', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Is_joined', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
